blank_issues_enabled: false
contact_links:
  - name: facileManager Community Support
    url: https://github.com/facileManager/facileManager/discussions
    about: Please ask and answer questions here.
  - name: facileManager Documentation
    url: https://docs.facilemanager.com
    about: Please read and review the documentation before opening an issue.
